"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _map_widget from './map-widget.bones.json'
import _github_graph from './github-graph.bones.json'

registerBones({
  "map-widget": _map_widget,
  "github-graph": _github_graph,
})
